import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Commerce from '@chec/commerce.js';
import { useEffect, useState } from 'react';
import { ProductCard } from '@/components/ProductCard/ProductCard';
import { Grid } from 'semantic-ui-react';

export default function Home() {
  const commerce = new Commerce('pk_test_51225484fc6d2262de162f37154363c2a1377c2486ea9');

  const [products, setProducts] = useState<any>([])

  useEffect(() => {
    commerce.products.list()
      .then(res => {
        setProducts(res.data)
        console.log(res.data)
      })
      .catch(err => console.log(err))
  }, [])

  return (
    <>
      <Head>
        <title>Garage Sell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Grid stackable columns='equal' centered>
          {/* <Image src={hero} fluid /> */}
          {products.map((product: any) => <Grid.Column width={5} key={product.id}><ProductCard product={product} /></Grid.Column>)}
        </Grid>
      </main>
    </>
  )
}
